### ISSUE TITLE
AWS Credentials exposed

### ISSUE THREAD

**Issue by csquared** [MarceloBentivoglio/mvpinvest#106]
https://github.com/MarceloBentivoglio/mvpinvest/blob/6a635a1a9c055a260808f3e0d33673cb6676cdf0/config/storage.yml#L9-L14

Hey there:

Your bucket credentails were publicly available so we rolled your keys - new ones are already in the ENV of your Heroku app. In the future, please do not commit your private keys to a public repo.
Thanks!

Cheers,
Chris

**Comment by joaquim-oliveira-neto** [comment]
Hey Chris, 

Thank you very much for the advise and for rolling our keys! It was very nice of you!

Cheers,
Joaquim
